language: ruby
cache: bundler
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
before_script:
- git config --global user.name rmpestano
- git config --global user.email rmpestano@gmail.com
env:
  global:
    secure: RdcmSu0rmwGgLxuRN+TfuIr6N3IGj7jS6fTEfDVkcMlpscEOQg6gt9fx/FG3T2F+fatXPnT1RQPQWOPyxB5fYGveySG9x5k+E0ffIj6DH2qKAZFc3GMoDI3s5l08M/TsF5w3qTJSDFyDTjIqFYdzDkVdaLxxVeqEQzlc5DMnaziiMtBYhRhdABo3WU4EcjO1lds9j4xNLciuUBRTJDDYxc6/OTZpp9CfCofJHgPpqGobmTonnc/k/AppHjyGJRRefPBi+VqofDXYzqiE8d6RAVbEKmR/CYDR1JNA/20nyZJrGQFjhEWIOc3PM9wDek1/w4im6Jr4t9/MeNrfTEoBkR4gq/BVcFS1E+klATYTkX+O+bphtjfdl33riYiy8P9dxXfVLqs3YY/ThHiqc70lfZg3s9LGPlXJtgHClckqeFX9BEsL4f9jc5mgxZ+GYVljneV5yAKbZY2T+h2++1cq88QZnvRGQp1DEtSNH22SQIpgaVWxAJx+2385W/RPDYJQ8COZDOJ5PxNAk0BNMzZvmUKw2bVH4PaljQxWrKUSeHmspSJ+GYmHy0gaqdcY+015IWq8u/3maRbD/4kgpx9rv4SzdDAq4etx7ugX8H5rdo5B4an0OA9QbSQ/za+l16FdND5iEnYmTRkJZ/+MqQDF4zgXWe0cpgBmes59m75PmW8=
